language: php

sudo: false
dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE ironman;'

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
